package:
  format-version: "1.0.0"
  name: "x2c"
  type: "api"
  status: "production"
  required: true
  version: "1.4.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "3.17.0"